#!/usr/bin/env bash
# Regenerate config/cli-backends.generated.patch.json5 with paths resolved for THIS machine.
#
#   scripts/render-cli-backends.sh
#
# The patch has to name absolute commands: the gateway runs under launchd or
# systemd with a minimal PATH, so a bare `codex` resolves differently there than
# in your shell — the failure this repo already hit with node. Absolute paths fix
# that and make the file machine-specific, which is why it is generated rather
# than hand-edited when moving to another box.
set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$DIR/config/cli-backends.generated.patch.json5"

find_bin() {  # $1 = binary name -> absolute path on stdout, empty if missing
  local found
  found="$(command -v "$1" 2>/dev/null || true)"
  if [ -z "$found" ]; then
    local candidate
    for candidate in "$HOME"/node/bin/"$1" "$HOME"/.nvm/versions/node/*/bin/"$1" /opt/homebrew/bin/"$1" /usr/local/bin/"$1" /usr/bin/"$1"; do
      [ -x "$candidate" ] && found="$candidate" && break
    done
  fi
  printf '%s\n' "$found"
}

CODEX="$(find_bin codex)"
DEEPSEEK="$(find_bin deepseek)"

[ -n "$CODEX" ] || { echo "not found: codex — install it first, or edit $OUT by hand" >&2; exit 1; }

# The qoder wrapper is looked up rather than assumed to sit in this repo. The
# server runs its own copy at ~/qoder-cli.sh and has only part of this repo
# checked out, so naming $DIR/scripts/qoder-cli.sh unconditionally pointed the
# config at a file that was not there — which takes Thợ out of the room with no
# error anywhere. Prefer the repo copy, accept the deployed one, refuse to guess.
QODER_WRAPPER=""
for candidate in "$DIR/scripts/qoder-cli.sh" "$HOME/qoder-cli.sh"; do
  [ -x "$candidate" ] && QODER_WRAPPER="$candidate" && break
done
[ -n "$QODER_WRAPPER" ] || {
  echo "not found: qoder-cli.sh in $DIR/scripts or $HOME — deploy it before rendering" >&2
  exit 1
}

CODEX_ARGS='"exec", "--skip-git-repo-check", "--dangerously-bypass-approvals-and-sandbox"'

DEEPSEEK_BLOCK=""
if [ -n "$DEEPSEEK" ]; then
  DEEPSEEK_BLOCK="        \"deepseek-cli\": {
          command: \"$DEEPSEEK\",
          args: [\"-p\", \"--yes\"],
          input: \"arg\",
          output: \"text\",
          modelArg: \"-m\",
          sessionMode: \"none\",
        },"
fi

cat > "$OUT" <<EOF
// Generated by scripts/render-cli-backends.sh — re-run it on a new machine.
{
  agents: {
    defaults: {
      cliBackends: {
        // This backend runs with the sandbox OFF, deliberately. Codex's
        // bubblewrap sandbox cannot create a namespace on the GCP VM, so
        // \`--sandbox read-only\` left Vé Tháng unable to run anything at all;
        // measured 18/8, the bypass flag is what made \`codex exec\` work there.
        //
        // State the cost plainly rather than let the old "read-only is the
        // boundary" comment keep standing: this backend can now run anything
        // the service user can. tools.deny never reaches a CLI backend
        // (docs/discord-setup.md), so nothing underneath catches a misread, and
        // the only boundary left is the guild allowlist — one Discord user id.
        // Scope every instruction narrowly, and prefer handing the agent a
        // fixed script name over a command line for it to assemble.
        //
        // --skip-git-repo-check: the agent workspace is not a git repo.
        "codex-cli": {
          command: "$CODEX",
          args: [$CODEX_ARGS],
          input: "arg",
          output: "text",
          modelArg: "--model",
          sessionMode: "none",
        },
$DEEPSEEK_BLOCK
        // Wrapper, not the binary: it loads the token before exec'ing qoder.
        "qoder-cli": {
          command: "$QODER_WRAPPER",
          args: ["-p", "--no-session-persistence"],
          input: "arg",
          output: "text",
          modelArg: "-m",
          sessionMode: "none",
        },
      },
    },
  },
}
EOF

echo "wrote $OUT"
echo "  codex-cli    -> $CODEX"
[ -n "$DEEPSEEK" ] && echo "  deepseek-cli -> $DEEPSEEK"
echo "  qoder-cli    -> $QODER_WRAPPER"
echo
echo "Check it before applying:  openclaw config patch --file config/cli-backends.generated.patch.json5 --dry-run"
